import { AirdropDetailType, AirdropItem } from '@/api/airdrop/types'

export const airdropData: AirdropItem[] = [
  {
    airdrop: [
      {
        contract: '',
        distribution_id: 0,
        is_all: false,
        type: AirdropDetailType.Kol,
      },
    ],
    airdrop_address: '',
    airdrop_index: 0,
    airdrop_supply: '',
    airdrop_type: 0,
    airdrop_version: '0.1.2',
    chain: '',
    coin_type: 0,
    coin_version: '0.1.2',
    contract_address: '',
    created_at: '',
    creator_address: '',
    description: '',
    factory_address: '',
    graduated_master: '',
    graduated_pool: '',
    graduated_token: '',
    hash: '',
    id: '0x0123abc',
    image_url:
      'https://storage.memehub.ai/uploads/otFf0o7r_400x400e8a0587db12b8f6792add2180bf6c5ff.jpg',
    is_active: true,
    is_graduated: false,
    max_supply: '',
    name: 'Cat',
    symbol: 'CAT',
    network: 'bsc',
    poster_urls: [],
    start_price: '',
    telegram_url: '',
    total_supply: '',
    twitter_url: '',
    updated_at: '',
    website_url: '',
  },
  {
    airdrop: [
      {
        contract: '',
        distribution_id: 0,
        is_all: false,
        type: AirdropDetailType.Kol,
      },
    ],
    airdrop_address: '',
    airdrop_index: 0,
    airdrop_supply: '',
    airdrop_type: 0,
    airdrop_version: '0.1.2',
    chain: '',
    coin_type: 0,
    coin_version: '0.1.2',
    contract_address: '',
    created_at: '',
    creator_address: '',
    description: '',
    factory_address: '',
    graduated_master: '',
    graduated_pool: '',
    graduated_token: '',
    hash: '',
    id: '0xfebece',
    image_url:
      'https://storage.memehub.ai/uploads/2023-03-03T183749Z_223809524_RC2GMZ9TFU26_RTRMADP_3_USA-ELECTION-KENNEDY-1711522461c54cfd953b7048e9b61c37bf840c7c96.webp',
    is_active: true,
    is_graduated: false,
    max_supply: '',
    name: 'Speak',
    network: 'bsc',
    poster_urls: [],
    start_price: '',
    symbol: 'SPK',
    telegram_url: '',
    total_supply: '',
    twitter_url: '',
    updated_at: '',
    website_url: '',
  },
  {
    airdrop: [
      {
        contract: '',
        distribution_id: 0,
        is_all: false,
        type: AirdropDetailType.Kol,
      },
    ],
    airdrop_address: '',
    airdrop_index: 0,
    airdrop_supply: '',
    airdrop_type: 0,
    airdrop_version: '0.1.2',
    chain: '',
    coin_type: 0,
    coin_version: '0.1.2',
    contract_address: '',
    created_at: '',
    creator_address: '',
    description: '',
    factory_address: '',
    graduated_master: '',
    graduated_pool: '',
    graduated_token: '',
    hash: '',
    id: '0xfebece',
    image_url:
      'https://s3.ap-east-1.amazonaws.com/storage.memehub.ai/uploads/0177b34d-1f7e-4875-8595-7d889f7990e2.jpg',
    is_active: true,
    is_graduated: false,
    max_supply: '',
    name: 'C',
    network: 'bsc',
    poster_urls: [],
    start_price: '',
    symbol: 'C',
    telegram_url: '',
    total_supply: '',
    twitter_url: '',
    updated_at: '',
    website_url: '',
  },
  {
    airdrop: [
      {
        contract: '',
        distribution_id: 0,
        is_all: false,
        type: AirdropDetailType.Kol,
      },
    ],
    airdrop_address: '',
    airdrop_index: 0,
    airdrop_supply: '',
    airdrop_type: 0,
    airdrop_version: '0.1.2',
    chain: '',
    coin_type: 0,
    coin_version: '0.1.2',
    contract_address: '',
    created_at: '',
    creator_address: '',
    description: '',
    factory_address: '',
    graduated_master: '',
    graduated_pool: '',
    graduated_token: '',
    hash: '',
    id: '0xfebece',
    image_url:
      'https://s3.ap-east-1.amazonaws.com/storage.memehub.ai/uploads/000049cbbb8e4e1889f61aa8914bd42669e258fde4a4e921c068d7bfa6ea6bf2.webp',
    is_active: true,
    is_graduated: false,
    max_supply: '',
    name: 'Dogecoin',
    network: 'bsc',
    poster_urls: [],
    start_price: '',
    symbol: 'DOGE',
    telegram_url: '',
    total_supply: '',
    twitter_url: '',
    updated_at: '',
    website_url: '',
  },
]
